/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_frameclient_utils_H264Decoder */

#ifndef _Included_com_frameclient_utils_H264Decoder
#define _Included_com_frameclient_utils_H264Decoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_frameclient_utils_H264Decoder
 * Method:    init
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_frameclient_utils_H264Decoder_init
  (JNIEnv *, jobject, jint, jint,jint,jint,jint,jint);

/*
 * Class:     com_frameclient_utils_H264Decoder
 * Method:    decode
 * Signature: ([BI[B)V
 */
JNIEXPORT jint JNICALL Java_com_frameclient_utils_H264Decoder_decode
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray,jint,jint,jint);

/*
 * Class:     com_frameclient_utils_H264Decoder
 * Method:    uninit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_frameclient_utils_H264Decoder_uninit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
