spring:
  application:
    name: hello-service
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      # defaultZone: http://localhost:1111/eureka/
      defaultZone: http://peer1:1111/eureka/,http://peer2:1112/eureka/
