spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sc?useUnicode\=true&amp;characterEncoding\=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql

    #druid参考官方配置
    initial-size: 1
    max-active: 20
    max-idle: 30
    min-idle: 5
    max-wait: 60000

    #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000

    #配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 'x'
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    pool-prepared-statements: false
    max-open-prepared-statements: 20

    #配置监控统计拦截的filters
    filters: stat

  redis:
    host: 118.31.164.36
    port: 6379
    password: zaq12wsx1111
    expire: 2592000
    timeout: 3000
    dbIndex: 0
    maxIdle: 300
    testOnBorrow: true
    maxTotal: 300
    maxWaitMillis: 3000
 
 
#日志
logging:
  config: classpath:logback-boot.xml
  
endpoints:
  shutdown:
    enabled: true
    sensitive: false
  